baseurl = "https://drewhamilton.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
isMultilingual = false
title = "Drew Hamilton"
theme = "sam"
pygmentsStyle = "native" # https://help.farbox.com/pygments.html
pygmentsCodefences = true
# googleAnalytics        = "" # Tracking code, eg. "UA-111111111-1"

[params]
    dateform = "Mon Jan 02, 2006"
    dateformfull = "Mon Jan 2 2006 15:04:05 EST"
#    favicon = "sam.ico"
    homepage = "Home"
#    footerText = ""

    # Metadata for Open Graph and Twitter
    description = "Drew's blog." # Max 160 characters show in search results
    # images = ["tn.png"] # Image that shows on Twitter cards and Open Graph links to the site
    title = "drewhamilton.dev"

[[params.mainMenu]]
    text = "Blog"
    link = "/posts"

[[params.mainMenu]]
    text = "GitHub"
    link = "https://github.com/drewhamilton"

[[params.mainMenu]]
    text = "Twitter"
    link = "https://twitter.com/AndroidHamilton"

[[params.mainMenu]]
    text = "About"
    link = "/about"
