baseURL = "https://drewhamilton.dev/"
title = "Drew Hamilton"
theme = "hugo-notepadium"
copyright = "©2020-2021 Drew Hamilton"

languageCode = "en-us"
defaultContentLanguage = "en"
isMultilingual = false

pygmentsStyle = "native" # https://help.farbox.com/pygments.html
pygmentsCodefences = true
# googleAnalytics        = "" # Tracking code, eg. "UA-111111111-1"

[params]
    dateFormat = "January 2, 2006"

    # Metadata for Open Graph and Twitter
    description = "Drew's blog." # Max 160 characters show in search results
    # images = ["tn.png"] # Image that shows on Twitter cards and Open Graph links to the site
    title = "drewhamilton.dev"

[[params.nav.custom]]
    title = "GitHub"
    url = "https://github.com/drewhamilton"

[[params.nav.custom]]
    title = "Twitter"
    url = "https://twitter.com/AndroidHamilton"
